main/urls.py
from django.conf.urls import url

from . import views
from .feed import LatestBlogEntriesFeed

# from django.views.decorators.cache import cache_page

urlpatterns = [
    # url(r'^drug/detail/(?P<pk>\d+)$', views.DrugDetail.as_view(), name='drug-detail'),
    url(r'^drug/list/$', views.PostList.as_view(), name='drug-list', kwargs={'post_type': 'drug'}),
    # url(r'^drug/list/letter/(?P<letter>[a-zа-я0-9])$', views.PostList.as_view(), kwargs={'action': 'alphabet', 'post_type': 'drug'}, name='drug-list-letter'),
    url(r'^drug/create/$', views.PostCreate.as_view(), name='drug-create', kwargs={'post_type': 'drug'}),
    url(r'^drug/update/(?P<pk>\d+)/$', views.PostUpdate.as_view(), name='drug-update', kwargs={'post_type': 'drug'}),
    url(r'^drug/list_ajax/$', views.PostListAjax.as_view(), name='drug-list-ajax', kwargs={'post_type': 'drug'}),

    url(r'^cosmetics/list/$', views.PostList.as_view(), name='cosmetics-list', kwargs={'post_type': 'cosmetics'}),
    # url(r'^cosmetics/list/letter/(?P<letter>[a-zа-я0-9])$', views.PostList.as_view(), kwargs={'action': 'alphabet', 'post_type': 'cosmetics'}, name='cosmetics-list-letter'),
    url(r'^cosmetics/create/$', views.PostCreate.as_view(), name='cosmetics-create', kwargs={'post_type': 'cosmetics'}),
    url(r'^cosmetics/update/(?P<pk>\d+)/$', views.PostUpdate.as_view(), name='cosmetics-update',
        kwargs={'post_type': 'cosmetics'}),
    url(r'^cosmetics/list_ajax/$', views.PostListAjax.as_view(), name='cosmetics-list-ajax',
        kwargs={'post_type': 'cosmetics'}),

    url(r'^blog/list/$', views.PostList.as_view(), name='blog-list', kwargs={'post_type': 'blog'}),
    url(r'^blog/create/$', views.PostCreate.as_view(), name='blog-create', kwargs={'post_type': 'blog'}),
    url(r'^blog/update/(?P<pk>\d+)/$', views.PostUpdate.as_view(), name='blog-update', kwargs={'post_type': 'blog'}),
    url(r'^blog/list_ajax/$', views.PostListAjax.as_view(), name='blog-list-ajax', kwargs={'post_type': 'blog'}),

    url(r'^component/list/$', views.PostList.as_view(), name='component-list', kwargs={'post_type': 'component'}),
    # url(r'^component/list/letter/(?P<letter>[a-zа-я0-9])$', views.PostList.as_view(), kwargs={'action': 'alphabet', 'post_type': 'component'}, name='component-list-letter'),
    url(r'^component/create/$', views.PostCreate.as_view(), name='component-create', kwargs={'post_type': 'component'}),
    url(r'^component/update/(?P<pk>\d+)/$', views.PostUpdate.as_view(), name='component-update',
        kwargs={'post_type': 'component'}),
    url(r'^component/list_ajax/$', views.PostListAjax.as_view(), name='component-list-ajax',
        kwargs={'post_type': 'component'}),

    url(r'^post/(?P<pk>\d+)/$', views.PostDetail.as_view(), kwargs={'action': 'normal'}, name='post-detail-pk'),
    url(r'^post/(?P<pk>\d+)/comment/(?P<comment_pk>\d+)/$', views.PostDetail.as_view(), kwargs={'action': 'comment'},
        name='post-detail-pk-comment'),

    url(r'^comment/get_for_answer_block_ajax/$', views.CommentGetForAnswerToBlockAjax.as_view(),
        name='comment-get-for-answer-block-ajax'),
    url(r'^comment/get_tree_ajax/$', views.CommentGetTreeAjax.as_view(), name='get-comment-tree-ajax'),

    url(r'^comment/update/(?P<pk>\d+)/$', views.CommentUpdate.as_view(), name='comment-update'),

    url(r'^comment/doctor_list/$', views.CommentDoctorListView.as_view(), name='comment-doctor-list'),

    url(r'^$', views.MainPageView.as_view(), name='main-page'),

    url(r'^rss/rss/$', LatestBlogEntriesFeed(), name='rss'),

    url(r'^search/', views.ProzdoSearchView.as_view(), name='search'),
    url(r'^autocomplete/$', views.ProzdoAutocompleteView.as_view(), name='autocomplete'),

]

urlpatterns.append(url(r'^(?P<alias>[a-z0-9_\-]{1,})/comment/(?P<comment_pk>\d+)/$', views.PostDetail.as_view(),
                       kwargs={'action': 'comment'}, name='post-detail-alias-comment'))
urlpatterns.append(url(r'^(?P<alias>[a-z0-9_\-]{1,})/$', views.PostDetail.as_view(), kwargs={'action': 'normal'},
                       name='post-detail-alias'))

prozdo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.decorators.cache import cache_page

from main.sitemaps import sitemaps

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    # url(r'^search/', include('haystack.urls')),
    url(r'^', include('super_model.urls')),
    url(r'^', include('main.urls')),
    url(r'^contact_form/', include('contact_form.urls', namespace="contact_form")),
    # url(r'^', include('main.urls')),
    url(r'^sitemap\.xml$', cache_page(60 * 60 * 12)(sitemap), {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

]

urlpatterns += [url(r'^ckeditor/', include('ckeditor_uploader.urls'))]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]

main/forms.py
from django import forms
from django.conf import settings

from super_model import fields as super_fields
from super_model import forms as super_forms
from . import models


class CommentForm(super_forms.SuperCommentForm):
    class Meta:
        model = models.Comment
        fields = ('username', 'email', 'body', 'post_mark', 'parent')

    def __init__(self, *args, request=None, post=None, **kwargs):
        super().__init__(*args, request=request, post=post, **kwargs)
        user = request.user

        # if not user.is_regular:
        #    del self.fields['consult_required']

        if post.get_mark_by_request(request):
            del self.fields['post_mark']


class CommentUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ('body',)


class CommentOptionsForm(super_forms.SuperCommentOptionsForm):
    show_type_label = 'Вид показа отзывов'


class DrugFilterForm(super_forms.PostFilterForm):
    class Meta:
        post_type = settings.POST_TYPE_DRUG

    dosage_forms = forms.ModelMultipleChoiceField(queryset=models.DrugDosageForm.objects.all(), label='Форма выпуска',
                                                  widget=forms.CheckboxSelectMultiple(), required=False)
    usage_areas = forms.ModelMultipleChoiceField(queryset=models.DrugUsageArea.objects.all(),
                                                 label='Область применения', widget=forms.CheckboxSelectMultiple(),
                                                 required=False)


class ComponentFilterForm(super_forms.PostFilterForm):
    class Meta:
        post_type = settings.POST_TYPE_COMPONENT

    component_type = forms.MultipleChoiceField(choices=models.COMPONENT_TYPES, label='Тип компонента',
                                               widget=forms.CheckboxSelectMultiple(), required=False)


class CosmeticsFilterForm(super_forms.PostFilterForm):
    class Meta:
        post_type = settings.POST_TYPE_COSMETICS

    brand = forms.ModelMultipleChoiceField(queryset=models.BrandModel.objects.all(), label='Бренд',
                                           widget=forms.CheckboxSelectMultiple(), required=False)
    line = forms.ModelMultipleChoiceField(queryset=models.CosmeticsLine.objects.all(), label='Линия',
                                          widget=forms.CheckboxSelectMultiple(), required=False)
    usage_areas = forms.ModelMultipleChoiceField(queryset=models.CosmeticsUsageArea.objects.all(),
                                                 label='Область применения', widget=forms.CheckboxSelectMultiple(),
                                                 required=False)
    dosage_forms = forms.ModelMultipleChoiceField(queryset=models.CosmeticsDosageForm.objects.all(),
                                                  label='Форма выпуска', widget=forms.CheckboxSelectMultiple(),
                                                  required=False)


class DrugForm(forms.ModelForm):
    class Meta:
        model = models.Drug
        exclude = ('post_type', 'old_id', 'created', 'updated', 'published')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['dosage_forms'].widget = forms.CheckboxSelectMultiple(
            choices=self.fields['dosage_forms'].widget.choices)
        self.fields['usage_areas'].widget = forms.CheckboxSelectMultiple(
            choices=self.fields['usage_areas'].widget.choices)
        self.fields['components'].widget = forms.CheckboxSelectMultiple(
            choices=self.fields['components'].widget.choices)
        self.fields['category'].widget = forms.CheckboxSelectMultiple(choices=self.fields['category'].widget.choices)
        self.fields['image'].widget = super_fields.SuperImageClearableFileInput(thumb_name='thumb110')


class CosmeticsForm(forms.ModelForm):
    class Meta:
        model = models.Cosmetics
        exclude = ('post_type', 'old_id', 'created', 'updated', 'published')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['dosage_forms'].widget = forms.CheckboxSelectMultiple(
            choices=self.fields['dosage_forms'].widget.choices)
        self.fields['usage_areas'].widget = forms.CheckboxSelectMultiple(
            choices=self.fields['usage_areas'].widget.choices)
        self.fields['image'].widget = super_fields.SuperImageClearableFileInput(thumb_name='thumb110')


class BlogForm(forms.ModelForm):
    class Meta:
        model = models.Blog
        exclude = ('post_type', 'old_id', 'created', 'updated', 'published')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['image'].widget = super_fields.SuperImageClearableFileInput(thumb_name='thumb110')
        self.fields['category'].widget = forms.CheckboxSelectMultiple(choices=self.fields['category'].widget.choices)


class ComponentForm(forms.ModelForm):
    class Meta:
        model = models.Component
        exclude = ('post_type', 'old_id', 'created', 'updated', 'published')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['component_type'].widget = forms.CheckboxSelectMultiple(choices=self.fields['component_type'].widget.choices)


BOOL_CHOICE_DEFAULT = 0
BOOL_CHOICE_NO = 1
BOOL_CHOICE_YES = 2

BOOL_CHOICES = (
    (BOOL_CHOICE_DEFAULT, 'Не выбрано'),
    (BOOL_CHOICE_YES, 'Да'),
    (BOOL_CHOICE_NO, 'Нет'),
)


class CommentDoctorListFilterForm(forms.Form):
    consult_required = forms.ChoiceField(label='Нужна консультация', required=False, choices=BOOL_CHOICES)
    consult_done = forms.ChoiceField(label='Консультация оказана', required=False, choices=BOOL_CHOICES)
    start_date = forms.DateField(label='Дата начала', required=False,
                                 widget=forms.DateInput(attrs={'class': 'date-input'}))
    end_date = forms.DateField(label='Дата окончания', required=False,
                               widget=forms.DateInput(attrs={'class': 'date-input'}))
    consult_only = forms.BooleanField(label='Только консультации', required=False)

super_model/forms.py
from django import forms
from haystack.forms import SearchForm
from allauth.account.forms import SignupForm
from . import fields
from django.contrib.auth.models import User
from django.utils.module_loading import import_string
from .app_settings import settings

UserProfile = import_string(settings.BASE_USER_PROFILE_CLASS)
Post = import_string(settings.BASE_POST_CLASS)
Comment = import_string(settings.BASE_COMMENT_CLASS)

class SuperSearchForm(SearchForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['q'].widget.attrs['placeholder'] = 'Поиск по сайту'
        self.fields['q'].widget.attrs['autocomplete'] = 'Off'

    def search(self):
        # First, store the SearchQuerySet received from other processing.
        sqs = super().search()

        return sqs

class SuperSignupForm(SignupForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'image':
                field.widget.attrs['placeholder'] = field.label


    required_css_class = 'required'
    image = forms.ImageField(label='Изображение', required=False)
    username = fields.UserNameField()

    def save(self, request, *args, **kwargs):
        user = super().save(request, *args, **kwargs)
        if 'image' in self.cleaned_data:
            user_profile = user.user_profile
            user_profile.image = self.cleaned_data['image']
            user_profile.save()
        return user


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('image', 'receive_messages')

    image = forms.ImageField(label='Изображение', widget=fields.SuperImageClearableFileInput(thumb_name='thumb100'), required=False)


class UserForm(forms.ModelForm):
    username = fields.UserNameField()
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name')


class PostFilterForm(forms.Form):
    alphabet = forms.MultipleChoiceField(choices=(), label='Алфавитный указатель', required=False, widget=forms.CheckboxSelectMultiple())
    title = forms.CharField(label='Название', required=False)

    def __init__(self, *args, alphabet=True, **kwargs):
        from string import digits, ascii_lowercase
        super().__init__(*args, **kwargs)
        post_type = self.Meta.post_type
        if alphabet:
            alph = ()
            letters = digits + ascii_lowercase + 'абвгдеёжзийклмнопрстуфхцчшщэюя'
            for letter in letters:
                posts = Post.objects.get_available().filter(post_type=post_type, title__istartswith=letter)
                count = posts.count()
                if count > 0:
                    alph += ((letter, '{0}({1})'.format(letter, count)), )
            self.fields['alphabet'] = forms.MultipleChoiceField(choices=alph, label='Алфавитный указатель', required=False, widget=forms.CheckboxSelectMultiple())


class CommentConfirmForm(forms.Form):
    email = forms.EmailField(label='Электронный адрес')
    comment = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=Comment.objects.all())


class SuperCommentForm(forms.ModelForm):
    required_css_class = 'required'
    class Meta:
        model = Comment
        fields = ('username', 'email', 'body', 'parent' )

    def __init__(self, *args, request=None, post=None, **kwargs):
        super().__init__(*args, **kwargs)
        user = request.user
        self.fields['parent'].widget = forms.HiddenInput()
        self.fields['parent'].queryset = post.comments.all()

        if user.is_authenticated():
            self.fields['username'].widget = forms.HiddenInput()
            self.fields['username'].initial = user.username
            self.fields['email'].widget = forms.HiddenInput()
            self.fields['email'].initial = user.email

COMMENTS_ORDER_BY_CREATED_DEC = 1
COMMENTS_ORDER_BY_CREATED_INC = 2


COMMENTS_ORDER_BY_CREATED_CHOICES = (
    (COMMENTS_ORDER_BY_CREATED_DEC, 'Последние отзывы сверху'),
    (COMMENTS_ORDER_BY_CREATED_INC, 'Последние отзывы снизу'),

)

COMMENTS_SHOW_TYPE_PLAIN = 1
COMMENTS_SHOW_TYPE_TREE = 2

COMMENTS_SHOW_TYPE_CHOICES = (
    (COMMENTS_SHOW_TYPE_PLAIN, 'Простой'),
    (COMMENTS_SHOW_TYPE_TREE, 'Деревом'),
)


class SuperCommentOptionsForm(forms.Form):
    show_type_label = 'Вид показа сообщений'
    order_by_created = forms.ChoiceField(choices=COMMENTS_ORDER_BY_CREATED_CHOICES, initial=COMMENTS_ORDER_BY_CREATED_DEC, label='Упорядочить по дате добавления', required=False)
    show_type= forms.ChoiceField(choices=COMMENTS_SHOW_TYPE_CHOICES, label=show_type_label, initial=COMMENTS_SHOW_TYPE_PLAIN, required=False)

main/templates/main/post/_component_list.html
<div class="clearfix">
    <table class="table">
        <thead>
        <tr>
            <th>Компонент</th>
            <th>Тип компонента</th>
        </tr>
        </thead>
        <tbody>
        {% for obj in objs %}
            <tr>
                <th><a href="{{ obj.get_absolute_url }}">{{ obj }}</a></th>
                <th>{{ obj.component_type_text }}</th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% include 'super_model/base/_pager.html' %}

main/templates/main/post/_post_list_ajax.html
{% include list_view_default_template with objs=objs %}

main/templates/main/post/_post_list_grid.html
<div class="clearfix">
    {% for obj in objs %}
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-6 post-grid-item">
            <div class="wrapper">
                <div class="post-info-grid">
                    <div class="image-wrapper"><a href="{{ obj.get_absolute_url }}"><img alt="{{ obj.title }}"
                                                                                         class="img-rounded"
                                                                                         src="{{ obj.thumb150 }}"></a>
                    </div>
                    <h5><a href="{{ obj.get_absolute_url }}">{{ obj }}</a></h5>
                </div>
                <div class="post-comment-count-grid">
                    <a href="{{ obj.get_absolute_url }}#comments">{{ obj.published_comments_count }}</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% include 'super_model/base/_pager.html' %}

main/templates/main/post/_recent_blogs.html
<div class="col-lg-6">
    <div class="blog-grid-main-item">
        <div class="wrapper">
            <div class="image-wrapper"><a href="{{ main_recent_blog.get_absolute_url }}"><img
                    alt="{{ main_recent_blog.title }}" class="img-rounded" src="{{ main_recent_blog.thumb360 }}"></a>
            </div>
            <h4><a href="{{ main_recent_blog.get_absolute_url }}">{{ main_recent_blog.title }}</a></h4>
            <h5><a href="{{ main_recent_blog.get_absolute_url }}">{{ main_recent_blog.anons }}</a></h5>
            <div class="post-comment-count-grid">
                <a href="{{ main_recent_blog.get_absolute_url }}#comments">{{ main_recent_blog.published_comments_count }}</a>
            </div>
        </div>
    </div>
</div>


<div class="col-lg-6">
    {% for obj in objs %}
        <div class="blog-grid-item">
            <div class="wrapper">
                <div class="image-wrapper"><a href="{{ obj.get_absolute_url }}"><img alt="{{ obj.title }}"
                                                                                     class="img-rounded"
                                                                                     src="{{ obj.thumb110 }}"></a></div>
                <h5><a href="{{ obj.get_absolute_url }}">{{ obj }}</a></h5>
                <h5><a href="{{ obj.get_absolute_url }}">{{ obj.anons }}</a></h5>

                <div class="post-comment-count-grid">
                    <a href="{{ obj.get_absolute_url }}#comments">{{ obj.published_comments_count }}</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

main/templates/main/post/post_create.html
{% extends base_template %}

{% block content %}
    <form enctype="multipart/form-data" id="post-create-form" method="post">
        {{ form.media }}
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Сохранить" class="btn btn-success">
    </form>
{% endblock content %}

main/templates/main/post/post_list.html
{% extends base_template %}
{% load main_tags %}
{% load compress %}
{% load staticfiles %}
{% block sidebar_left %}

    {% if post_type == 'drug' or post_type == 'cosmetics' or post_type == 'component' %}
        <div>

            <form id="post-list-form" method="get" action="{{ submit_url }}">

                {{ filter_form.as_p }}
                <a class="btn btn-default" href="{{ submit_url }}">Cбросить фильтр</a>
            </form>

        </div>
    {% endif %}


    {{ block.super }}
{% endblock sidebar_left %}


{% block content %}

    <div id="post-list">
        {% include list_view_default_template with objs=objs %}
    </div>


{% endblock content %}

{% block bottom_scripts %}

    {{ block.super }}
    {% compress js %}
        <script src='{% static "main/js/history.js/scripts/bundled/html4+html5/jquery.history.js" %}'></script>
        <script>
            $(function () {


                $('#post-list-form').on('submit', function (e) {

                    e.preventDefault();
                    return false;

                });


                function alphabetChanger() {

                    var checkedArr = [];

                    $('#id_alphabet').find('input:checkbox:checked').each(function () {
                        checkedArr.push($(this).val());
                    });
                    if (checkedArr.length > 0) {
                        $('#id_title').addClass('hidden').val('').prev('label').addClass('hidden');


                    }
                    else {
                        $('#id_title').removeClass('hidden').prev('label').removeClass('hidden');

                    }

                }


                function titleChanger() {
                    if ($('#id_title').val() != '') {
                        var alphabetBlock = $('#id_alphabet')
                        alphabetBlock.find('input:checkbox:checked').each(function () {
                            $(this).prop('checked', false)


                        });
                        alphabetBlock.addClass('hidden').prev('label').addClass('hidden');
                    }
                    else {
                        $('#id_alphabet').removeClass('hidden').prev('label').removeClass('hidden');
                    }

                }

                $('#id_alphabet').find('input').change(function (e) {

                    alphabetChanger();

                });


                $('#id_title').change(function (e) {
                    titleChanger();
                });

                $(document).on('change', '#post-list-form input', function (e) {
                    var frm = $('#post-list-form');
                    var url_data_params = '';
                    var cleanParamsArray = [];
                    var paramsArray = frm.serializeArray();
                    paramsArray.forEach(function (param) {
                        if (param.value) {
                            cleanParamsArray.push(param);

                        }
                    });

                    var url_data = $.param(cleanParamsArray);
                    if (url_data.length > 0) {
                        url_data_params = '?' + url_data;
                    }
                    else {
                        url_data_params = url_data;
                    }

                    frm.find('input').attr("disabled", true);
                    var title = $(document).find("title").text();

                    History.pushState(null, title, window.location.pathname + url_data_params);

                    $.ajax({
                        type: 'POST',
                        url: '{{ ajax_submit_url }}',
                        data: url_data,
                        success: function (data) {
                            $('#post-list').html(data);
                            frm.find('input').attr("disabled", false);
                        },
                        error: function (data) {
                            frm.find('input').attr("disabled", false);
                        }
                    });


                });

                titleChanger();
                alphabetChanger();
            });

        </script>
    {% endcompress %}
{% endblock bottom_scripts %}